### PR TITLE
Enable some keys back

### LINKED ISSUE #3: Usability problems
PLEASE
ENABLE
THE
ARROWS
BACK

### PR DESCRIPTION
**Pull request by esdrasbeleza**
The world is a better place this way.

Closes #3

### CODE REVIEW

**Comment by edgurgel** [comment]
https://github.com/edgurgel/vim-files/commit/974abf7c73e80eabb6ce85ef0b1b4fb51ebf6483

**Comment by edgurgel** [comment]
I keep merging iurifq's master but with my preferences :+1:

**Comment by iurifq** [comment]
@esdrasbeleza sorry for the late reply. I was traveling.

Unfortunately, I can't merge this :pensive:. That's not the way I use vim. The main idea of not using the arrow keys is not to take your hand out of the same position. You have to get used to it, but once you do it will be much more comfortable and fast. I disabled them to get rid of the habit of moving my hand out of the position.

Vim has other features to compensate that. You can check more here http://superuser.com/questions/599150/why-arrow-keys-are-not-recommended-in-vim

Closes #3

**Comment by iurifq** [comment]
@edgurgel you don't need to alter the repo's files to enable back the arrows, you can place your local configurations in `.vimrc.local` file in your home folder. This way you can keep in sync with my repo.

https://github.com/iurifq/vim-files/blob/4a9a9dd75c9e8ba01954fe8a9ecba1965b4c1721/vimrc#L9-L12

**Comment by edgurgel** [comment]
@iurifq, that's nice! I will take a look at this later. Cheers!

**Pull request closed without merging**
